# <div style="padding:20px;color:white;margin:0;font-size:30px;font-family:Georgia;text-align:left;display:fill;border-radius:5px;background-color:#7b6b59;overflow:hidden">NORMALIZE</div>

In [1]:
import pandas as pd
import numpy as np


r = range(2023, 2012-1, -1)
df = [pd.read_csv(f"egmo/egmo{i}.csv") for i in r]
max_possible_point = 7

In [2]:
# This cell is not used, ONLY for display
temp_dict = {
    "year": [i for i in r],
    "all": [],
    "normalized_p1": [],
    "normalized_p2": [],
    "normalized_p3": [],
    "normalized_p4": [],
    "normalized_p5": [],
    "normalized_p6": [],
    "normalized_p7": [],
    "normalized_p8": [],
}
for i, year in enumerate(temp_dict["year"]):
    if year == 2012:
        temp_dict["all"].append(df[i].shape[0])
        temp_dict["normalized_p1"].append((1-(df[i].P1.mean()/max_possible_point))*10)
        temp_dict["normalized_p2"].append((1-(df[i].P2.mean()/max_possible_point))*10)
        temp_dict["normalized_p3"].append((1-(df[i].P3.mean()/max_possible_point))*10)
        temp_dict["normalized_p4"].append((1-(df[i].P4.mean()/max_possible_point))*10)
        temp_dict["normalized_p5"].append((1-(df[i].P5.mean()/max_possible_point))*10)
        temp_dict["normalized_p6"].append((1-(df[i].P6.mean()/max_possible_point))*10)
        temp_dict["normalized_p7"].append((1-(df[i].P7.mean()/max_possible_point))*10)
        temp_dict["normalized_p8"].append((1-(df[i].P8.mean()/max_possible_point))*10)
        continue
    
    temp_dict["all"].append(df[i].shape[0])
    temp_dict["normalized_p1"].append((1-(df[i].P1.mean()/max_possible_point))*10)
    temp_dict["normalized_p2"].append((1-(df[i].P2.mean()/max_possible_point))*10)
    temp_dict["normalized_p3"].append((1-(df[i].P3.mean()/max_possible_point))*10)
    temp_dict["normalized_p4"].append((1-(df[i].P4.mean()/max_possible_point))*10)
    temp_dict["normalized_p5"].append((1-(df[i].P5.mean()/max_possible_point))*10)
    temp_dict["normalized_p6"].append((1-(df[i].P6.mean()/max_possible_point))*10)
    temp_dict["normalized_p7"].append(None)
    temp_dict["normalized_p8"].append(None)
    
pd.DataFrame(temp_dict)

,year,all,normalized_p1,normalized_p2,normalized_p3,normalized_p4,normalized_p5,normalized_p6,normalized_p7,normalized_p8
0,2023,213,5.063716,4.728370,6.130114,3.983903,5.767941,7.055667,NaN,NaN
1,2022,222,3.326898,7.792793,8.880309,2.979408,6.885457,8.500644,NaN,NaN
2,2021,213,6.646546,7.270288,8.832998,5.580148,8.222669,9.490275,NaN,NaN
3,2020,204,4.313725,8.823529,7.703081,5.735294,5.105042,9.733894,NaN,NaN
4,2019,196,3.075802,6.348397,7.820700,2.405248,7.026239,9.395044,NaN,NaN
5,2018,195,1.780220,6.256410,8.080586,3.838828,6.857143,9.172161,NaN,NaN
6,2017,168,1.947279,7.865646,8.265306,6.709184,7.431973,8.426871,NaN,NaN
7,2016,147,5.986395,6.190476,8.688047,5.276968,6.938776,8.775510,NaN,NaN
8,2015,109,3.800786,7.536042,8.479685,4.980341,6.959371,9.017038,NaN,NaN
9,2014,110,6.844156,8.025974,9.532468,6.467532,6.116883,8.857143,NaN,NaN
10,2013,87,1.231527,4.269294,9.392447,3.990148,8.669951,9.129721,NaN,NaN
11,2012,70,3.857143,5.877551,7.632653,9.918367,5.020408,6.469388,7.061224,9.857143

In [3]:
scores = []

for i, year in enumerate(r):
    scores.append((1-(df[i].P1.mean()/max_possible_point))*10)
    scores.append((1-(df[i].P2.mean()/max_possible_point))*10)
    scores.append((1-(df[i].P3.mean()/max_possible_point))*10)
    scores.append((1-(df[i].P4.mean()/max_possible_point))*10)
    scores.append((1-(df[i].P5.mean()/max_possible_point))*10)
    scores.append((1-(df[i].P6.mean()/max_possible_point))*10)
    if year == 2012:
        scores.append((1-(df[i].P7.mean()/max_possible_point))*10)
        scores.append((1-(df[i].P8.mean()/max_possible_point))*10)

print(scores)

[5.063715627095908, 4.7283702213279675, 6.130114017437962, 3.9839034205231383, 5.767940979208586, 7.0556673373574785, 3.326898326898328, 7.792792792792794, 8.880308880308881, 2.979407979407979, 6.885456885456885, 8.500643500643502, 6.646545942320589, 7.270288397048961, 8.832997987927566, 5.580147551978538, 8.222669349429912, 9.49027498323273, 4.313725490196079, 8.823529411764707, 7.7030812324929965, 5.735294117647058, 5.105042016806722, 9.733893557422968, 3.0758017492711365, 6.348396501457726, 7.820699708454811, 2.405247813411079, 7.026239067055393, 9.395043731778426, 1.7802197802197806, 6.256410256410256, 8.08058608058608, 3.8388278388278394, 6.857142857142858, 9.172161172161172, 1.947278911564626, 7.865646258503402, 8.26530612244898, 6.709183673469388, 7.431972789115646, 8.42687074829932, 5.986394557823129, 6.190476190476191, 8.68804664723032, 5.276967930029155, 6.938775510204081, 8.775510204081632, 3.800786369593708, 7.536041939711664, 8.479685452162517, 4.980340760157274, 6.9593709043250325, 9.017038007863697, 6.844155844155844, 8.025974025974026, 9.532467532467532, 6.467532467532467, 6.116883116883116, 8.857142857142858, 1.2315270935960587, 4.269293924466338, 9.392446633825944, 3.9901477832512313, 8.669950738916256, 9.129720853858785, 3.8571428571428577, 5.877551020408163, 7.63265306122449, 9.918367346938776, 5.020408163265307, 6.469387755102041, 7.061224489795919, 9.857142857142858]

# <div style="padding:20px;color:white;margin:0;font-size:30px;font-family:Georgia;text-align:left;display:fill;border-radius:5px;background-color:#7b6b59;overflow:hidden">COMBINE</div>

In [4]:
egmo = pd.read_csv("egmo/egmo.csv")
egmo['score'] = scores

# <div style="padding:20px;color:white;margin:0;font-size:30px;font-family:Georgia;text-align:left;display:fill;border-radius:5px;background-color:#7b6b59;overflow:hidden">DISCRETIZE</div>

In [5]:
from utils.discretizer import discretize

egmo["level"] = egmo.score.apply(discretize)

In [6]:
egmo.to_csv("../data/regression/egmo/egmo_combined.csv", index=False)